Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

Namespace BOLETAS

    '------------------------------------------------------------------------------
    ' <auto-generated>
    '     Este código fue generado por una herramienta.
    '     Versión de runtime:4.0.30319.42000
    '
    '     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
    '     se vuelve a generar el código.
    ' </auto-generated>
    '------------------------------------------------------------------------------


    '
    'Este código fuente fue generado automáticamente por xsd, Versión=4.7.2053.0.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
 System.Xml.Serialization.XmlRootAttribute("Signature", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignatureType

        Private signedInfoField As SignatureTypeSignedInfo

        Private signatureValueField() As Byte

        Private keyInfoField As SignatureTypeKeyInfo

        '''<remarks/>
        Public Property SignedInfo() As SignatureTypeSignedInfo
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property SignatureValue() As Byte()
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property KeyInfo() As SignatureTypeKeyInfo
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfo

        Private canonicalizationMethodField As SignatureTypeSignedInfoCanonicalizationMethod

        Private signatureMethodField As SignatureTypeSignedInfoSignatureMethod

        Private referenceField As SignatureTypeSignedInfoReference

        '''<remarks/>
        Public Property CanonicalizationMethod() As SignatureTypeSignedInfoCanonicalizationMethod
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureMethod() As SignatureTypeSignedInfoSignatureMethod
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Reference() As SignatureTypeSignedInfoReference
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfoCanonicalizationMethod

        Private algorithmField As String

        Public Sub New()
            MyBase.New
            Me.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfoSignatureMethod

        Private algorithmField As SignatureTypeSignedInfoSignatureMethodAlgorithm

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property Algorithm() As SignatureTypeSignedInfoSignatureMethodAlgorithm
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Public Enum SignatureTypeSignedInfoSignatureMethodAlgorithm

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")>
        httpwwww3org200009xmldsigrsasha1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#dsa-sha1")>
        httpwwww3org200009xmldsigdsasha1
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfoReference

        Private transformsField As SignatureTypeSignedInfoReferenceTransforms

        Private digestMethodField As SignatureTypeSignedInfoReferenceDigestMethod

        Private digestValueField() As Byte

        Private uRIField As String

        '''<remarks/>
        Public Property Transforms() As SignatureTypeSignedInfoReferenceTransforms
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DigestMethod() As SignatureTypeSignedInfoReferenceDigestMethod
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfoReferenceTransforms

        Private transformField As SignatureTypeSignedInfoReferenceTransformsTransform

        '''<remarks/>
        Public Property Transform() As SignatureTypeSignedInfoReferenceTransformsTransform
            Get
                Return Me.transformField
            End Get
            Set
                Me.transformField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfoReferenceTransformsTransform

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeSignedInfoReferenceDigestMethod

        Private algorithmField As String

        Public Sub New()
            MyBase.New
            Me.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeKeyInfo

        Private keyValueField As SignatureTypeKeyInfoKeyValue

        Private x509DataField As SignatureTypeKeyInfoX509Data

        '''<remarks/>
        Public Property KeyValue() As SignatureTypeKeyInfoKeyValue
            Get
                Return Me.keyValueField
            End Get
            Set
                Me.keyValueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property X509Data() As SignatureTypeKeyInfoX509Data
            Get
                Return Me.x509DataField
            End Get
            Set
                Me.x509DataField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeKeyInfoKeyValue

        Private itemField As Object

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(SignatureTypeKeyInfoKeyValueDSAKeyValue)),
     System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(SignatureTypeKeyInfoKeyValueRSAKeyValue))>
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeKeyInfoKeyValueDSAKeyValue

        Private pField() As Byte

        Private qField() As Byte

        Private gField() As Byte

        Private yField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set
                Me.qField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set
                Me.gField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set
                Me.yField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeKeyInfoKeyValueRSAKeyValue

        Private modulusField() As Byte

        Private exponentField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class SignatureTypeKeyInfoX509Data

        Private x509CertificateField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property X509Certificate() As Byte()
            Get
                Return Me.x509CertificateField
            End Get
            Set
                Me.x509CertificateField = Value
            End Set
        End Property
    End Class

    '''<remarks> 
    '''System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte"),
    '''System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sii.cl/SiiDte", IsNullable:=False)>
    '''</remarks>
    '''
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class EnvioBOLETA

        Private setDTEField As EnvioBOLETASetDTE

        Private signatureField As SignatureType

        Private versionField As Decimal

        Public Sub New()
            MyBase.New
            Me.versionField = CType(1D, Decimal)
        End Sub

        '''<remarks/>
        Public Property SetDTE() As EnvioBOLETASetDTE
            Get
                Return Me.setDTEField
            End Get
            Set
                Me.setDTEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property version() As Decimal
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class EnvioBOLETASetDTE

        Private caratulaField As EnvioBOLETASetDTECaratula

        Private dTEField() As BOLETADefType

        Private idField As String

        '''<remarks/>
        Public Property Caratula() As EnvioBOLETASetDTECaratula
            Get
                Return Me.caratulaField
            End Get
            Set
                Me.caratulaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DTE")>
        Public Property DTE() As BOLETADefType()
            Get
                Return Me.dTEField
            End Get
            Set
                Me.dTEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class EnvioBOLETASetDTECaratula

        Private rutEmisorField As String

        Private rutEnviaField As String

        Private rutReceptorField As String

        Private fchResolField As Date

        Private nroResolField As String

        Private tmstFirmaEnvField As Date

        Private subTotDTEField() As EnvioBOLETASetDTECaratulaSubTotDTE

        Private versionField As Decimal

        Public Sub New()
            MyBase.New
            Me.versionField = CType(1D, Decimal)
        End Sub

        '''<remarks/>
        Public Property RutEmisor() As String
            Get
                Return Me.rutEmisorField
            End Get
            Set
                Me.rutEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RutEnvia() As String
            Get
                Return Me.rutEnviaField
            End Get
            Set
                Me.rutEnviaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RutReceptor() As String
            Get
                Return Me.rutReceptorField
            End Get
            Set
                Me.rutReceptorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property FchResol() As Date
            Get
                Return Me.fchResolField
            End Get
            Set
                Me.fchResolField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property NroResol() As String
            Get
                Return Me.nroResolField
            End Get
            Set
                Me.nroResolField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TmstFirmaEnv() As Date
            Get
                Return Me.tmstFirmaEnvField
            End Get
            Set
                Me.tmstFirmaEnvField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SubTotDTE")>
        Public Property SubTotDTE() As EnvioBOLETASetDTECaratulaSubTotDTE()
            Get
                Return Me.subTotDTEField
            End Get
            Set
                Me.subTotDTEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property version() As Decimal
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class EnvioBOLETASetDTECaratulaSubTotDTE

        Private tpoDTEField As DTEType

        Private nroDTEField As String

        '''<remarks/>
        Public Property TpoDTE() As DTEType
            Get
                Return Me.tpoDTEField
            End Get
            Set
                Me.tpoDTEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property NroDTE() As String
            Get
                Return Me.nroDTEField
            End Get
            Set
                Me.nroDTEField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum DTEType

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("39")>
        Item39

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("41")>
        Item41
    End Enum

    '''<remarks>
    '''</remarks>
    '''
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
    System.SerializableAttribute(),
    System.Diagnostics.DebuggerStepThroughAttribute(),
    System.ComponentModel.DesignerCategoryAttribute("code"),
    System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sii.cl/SiiDte"),
    System.Xml.Serialization.XmlRootAttribute("DTE", [Namespace]:="http://www.sii.cl/SiiDte", IsNullable:=False)>
    Partial Public Class BOLETADefType

        Private documentoField As BOLETADefTypeDocumento

        Private signatureField As SignatureType

        Private versionField As String ' Decimal

        Public Sub New()
            MyBase.New
            Me.versionField = "1.0" 'CType(1D, Decimal)
        End Sub

        '''<remarks/>
        Public Property Documento() As BOLETADefTypeDocumento
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property version() As String ' Decimal
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumento

        Private encabezadoField As BOLETADefTypeDocumentoEncabezado

        Private detalleField() As BOLETADefTypeDocumentoDetalle

        Private subTotInfoField() As BOLETADefTypeDocumentoSubTotInfo

        Private dscRcgGlobalField() As BOLETADefTypeDocumentoDscRcgGlobal

        Private referenciaField() As BOLETADefTypeDocumentoReferencia

        Private adicionalField As DTEDocumentoAdicional

        Private tEDField As BOLETADefTypeDocumentoTED

        Private tmstFirmaField As Date

        Private idField As String

        '''<remarks/>
        Public Property Encabezado() As BOLETADefTypeDocumentoEncabezado
            Get
                Return Me.encabezadoField
            End Get
            Set
                Me.encabezadoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Detalle")>
        Public Property Detalle() As BOLETADefTypeDocumentoDetalle()
            Get
                Return Me.detalleField
            End Get
            Set
                Me.detalleField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SubTotInfo")>
        Public Property SubTotInfo() As BOLETADefTypeDocumentoSubTotInfo()
            Get
                Return Me.subTotInfoField
            End Get
            Set
                Me.subTotInfoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DscRcgGlobal")>
        Public Property DscRcgGlobal() As BOLETADefTypeDocumentoDscRcgGlobal()
            Get
                Return Me.dscRcgGlobalField
            End Get
            Set
                Me.dscRcgGlobalField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Referencia")>
        Public Property Referencia() As BOLETADefTypeDocumentoReferencia()
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Adicional() As DTEDocumentoAdicional
            Get
                Return Me.adicionalField
            End Get
            Set
                Me.adicionalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TED() As BOLETADefTypeDocumentoTED
            Get
                Return Me.tEDField
            End Get
            Set
                Me.tEDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TmstFirma() As Date
            Get
                Return Me.tmstFirmaField
            End Get
            Set
                Me.tmstFirmaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoEncabezado

        Private idDocField As BOLETADefTypeDocumentoEncabezadoIdDoc

        Private emisorField As BOLETADefTypeDocumentoEncabezadoEmisor

        Private receptorField As BOLETADefTypeDocumentoEncabezadoReceptor

        Private totalesField As BOLETADefTypeDocumentoEncabezadoTotales

        '''<remarks/>
        Public Property IdDoc() As BOLETADefTypeDocumentoEncabezadoIdDoc
            Get
                Return Me.idDocField
            End Get
            Set
                Me.idDocField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Emisor() As BOLETADefTypeDocumentoEncabezadoEmisor
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Receptor() As BOLETADefTypeDocumentoEncabezadoReceptor
            Get
                Return Me.receptorField
            End Get
            Set
                Me.receptorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Totales() As BOLETADefTypeDocumentoEncabezadoTotales
            Get
                Return Me.totalesField
            End Get
            Set
                Me.totalesField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoEncabezadoIdDoc

        Private tipoDTEField As DTEType

        Private folioField As String

        Private fchEmisField As Date

        Private indServicioField As BOLETADefTypeDocumentoEncabezadoIdDocIndServicio

        Private indMntNetoField As BOLETADefTypeDocumentoEncabezadoIdDocIndMntNeto

        Private indMntNetoFieldSpecified As Boolean

        Private periodoDesdeField As Date

        Private periodoDesdeFieldSpecified As Boolean

        Private periodoHastaField As Date

        Private periodoHastaFieldSpecified As Boolean

        Private fchVencField As Date

        Private fchVencFieldSpecified As Boolean

        '''<remarks/>
        Public Property TipoDTE() As DTEType
            Get
                Return Me.tipoDTEField
            End Get
            Set
                Me.tipoDTEField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property FchEmis() As Date
            Get
                Return Me.fchEmisField
            End Get
            Set
                Me.fchEmisField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IndServicio() As BOLETADefTypeDocumentoEncabezadoIdDocIndServicio
            Get
                Return Me.indServicioField
            End Get
            Set
                Me.indServicioField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IndMntNeto() As BOLETADefTypeDocumentoEncabezadoIdDocIndMntNeto
            Get
                Return Me.indMntNetoField
            End Get
            Set
                Me.indMntNetoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property IndMntNetoSpecified() As Boolean
            Get
                Return Me.indMntNetoFieldSpecified
            End Get
            Set
                Me.indMntNetoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property PeriodoDesde() As Date
            Get
                Return Me.periodoDesdeField
            End Get
            Set
                Me.periodoDesdeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property PeriodoDesdeSpecified() As Boolean
            Get
                Return Me.periodoDesdeFieldSpecified
            End Get
            Set
                Me.periodoDesdeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property PeriodoHasta() As Date
            Get
                Return Me.periodoHastaField
            End Get
            Set
                Me.periodoHastaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property PeriodoHastaSpecified() As Boolean
            Get
                Return Me.periodoHastaFieldSpecified
            End Get
            Set
                Me.periodoHastaFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property FchVenc() As Date
            Get
                Return Me.fchVencField
            End Get
            Set
                Me.fchVencField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property FchVencSpecified() As Boolean
            Get
                Return Me.fchVencFieldSpecified
            End Get
            Set
                Me.fchVencFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoEncabezadoIdDocIndServicio

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>
        Item2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3")>
        Item3

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("4")>
        Item4
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoEncabezadoIdDocIndMntNeto

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>
        Item2
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoEncabezadoEmisor

        Private rUTEmisorField As String

        Private rznSocEmisorField As String

        Private giroEmisorField As String

        Private cdgSIISucurField As String

        Private dirOrigenField As String

        Private cmnaOrigenField As String

        Private ciudadOrigenField As String

        Private sucursalField As String

        '''<remarks/>
        Public Property RUTEmisor() As String
            Get
                Return Me.rUTEmisorField
            End Get
            Set
                Me.rUTEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RznSocEmisor() As String
            Get
                Return Me.rznSocEmisorField
            End Get
            Set
                Me.rznSocEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property GiroEmisor() As String
            Get
                Return Me.giroEmisorField
            End Get
            Set
                Me.giroEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property CdgSIISucur() As String
            Get
                Return Me.cdgSIISucurField
            End Get
            Set
                Me.cdgSIISucurField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DirOrigen() As String
            Get
                Return Me.dirOrigenField
            End Get
            Set
                Me.dirOrigenField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CmnaOrigen() As String
            Get
                Return Me.cmnaOrigenField
            End Get
            Set
                Me.cmnaOrigenField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CiudadOrigen() As String
            Get
                Return Me.ciudadOrigenField
            End Get
            Set
                Me.ciudadOrigenField = Value
            End Set
        End Property

        '''<remarks></remarks>
        Public Property Sucursal() As String
            Get
                Return Me.sucursalField
            End Get
            Set
                Me.sucursalField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoEncabezadoReceptor

        Private rUTRecepField As String

        Private cdgIntRecepField As String

        Private rznSocRecepField As String

        Private contactoField As String

        Private dirRecepField As String

        Private cmnaRecepField As String

        Private ciudadRecepField As String

        Private dirPostalField As String

        Private cmnaPostalField As String

        Private ciudadPostalField As String

        '''<remarks/>
        Public Property RUTRecep() As String
            Get
                Return Me.rUTRecepField
            End Get
            Set
                Me.rUTRecepField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CdgIntRecep() As String
            Get
                Return Me.cdgIntRecepField
            End Get
            Set
                Me.cdgIntRecepField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RznSocRecep() As String
            Get
                Return Me.rznSocRecepField
            End Get
            Set
                Me.rznSocRecepField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Contacto() As String
            Get
                Return Me.contactoField
            End Get
            Set
                Me.contactoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DirRecep() As String
            Get
                Return Me.dirRecepField
            End Get
            Set
                Me.dirRecepField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CmnaRecep() As String
            Get
                Return Me.cmnaRecepField
            End Get
            Set
                Me.cmnaRecepField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CiudadRecep() As String
            Get
                Return Me.ciudadRecepField
            End Get
            Set
                Me.ciudadRecepField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DirPostal() As String
            Get
                Return Me.dirPostalField
            End Get
            Set
                Me.dirPostalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CmnaPostal() As String
            Get
                Return Me.cmnaPostalField
            End Get
            Set
                Me.cmnaPostalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CiudadPostal() As String
            Get
                Return Me.ciudadPostalField
            End Get
            Set
                Me.ciudadPostalField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoEncabezadoTotales

        Private mntNetoField As String

        Private mntExeField As String

        Private iVAField As String

        Private mntTotalField As String

        Private montoNFField As String

        Private totalPeriodoField As String

        Private saldoAnteriorField As String

        Private vlrPagarField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property MntNeto() As String
            Get
                Return Me.mntNetoField
            End Get
            Set
                Me.mntNetoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property MntExe() As String
            Get
                Return Me.mntExeField
            End Get
            Set
                Me.mntExeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property IVA() As String
            Get
                Return Me.iVAField
            End Get
            Set
                Me.iVAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property MntTotal() As String
            Get
                Return Me.mntTotalField
            End Get
            Set
                Me.mntTotalField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>
        Public Property MontoNF() As String
            Get
                Return Me.montoNFField
            End Get
            Set
                Me.montoNFField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property TotalPeriodo() As String
            Get
                Return Me.totalPeriodoField
            End Get
            Set
                Me.totalPeriodoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>
        Public Property SaldoAnterior() As String
            Get
                Return Me.saldoAnteriorField
            End Get
            Set
                Me.saldoAnteriorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>
        Public Property VlrPagar() As String
            Get
                Return Me.vlrPagarField
            End Get
            Set
                Me.vlrPagarField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoDetalle

        Private nroLinDetField As String

        Private cdgItemField() As BOLETADefTypeDocumentoDetalleCdgItem

        Private indExeField As BOLETADefTypeDocumentoDetalleIndExe

        Private indExeFieldSpecified As Boolean

        Private itemEspectaculoField As BOLETADefTypeDocumentoDetalleItemEspectaculo

        Private itemEspectaculoFieldSpecified As Boolean

        Private rUTMandanteField As String

        Private nmbItemField As String

        Private infoTicketField As BOLETADefTypeDocumentoDetalleInfoTicket

        Private dscItemField As String

        Private qtyItemField As Decimal

        Private qtyItemFieldSpecified As Boolean

        Private unmdItemField As String

        Private prcItemField As Decimal

        Private prcItemFieldSpecified As Boolean

        Private descuentoPctField As Decimal

        Private descuentoPctFieldSpecified As Boolean

        Private descuentoMontoField As String

        Private recargoPctField As Decimal

        Private recargoPctFieldSpecified As Boolean

        Private recargoMontoField As String

        Private montoItemField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property NroLinDet() As String
            Get
                Return Me.nroLinDetField
            End Get
            Set
                Me.nroLinDetField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CdgItem")>
        Public Property CdgItem() As BOLETADefTypeDocumentoDetalleCdgItem()
            Get
                Return Me.cdgItemField
            End Get
            Set
                Me.cdgItemField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IndExe() As BOLETADefTypeDocumentoDetalleIndExe
            Get
                Return Me.indExeField
            End Get
            Set
                Me.indExeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property IndExeSpecified() As Boolean
            Get
                Return Me.indExeFieldSpecified
            End Get
            Set
                Me.indExeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ItemEspectaculo() As BOLETADefTypeDocumentoDetalleItemEspectaculo
            Get
                Return Me.itemEspectaculoField
            End Get
            Set
                Me.itemEspectaculoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemEspectaculoSpecified() As Boolean
            Get
                Return Me.itemEspectaculoFieldSpecified
            End Get
            Set
                Me.itemEspectaculoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RUTMandante() As String
            Get
                Return Me.rUTMandanteField
            End Get
            Set
                Me.rUTMandanteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NmbItem() As String
            Get
                Return Me.nmbItemField
            End Get
            Set
                Me.nmbItemField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InfoTicket() As BOLETADefTypeDocumentoDetalleInfoTicket
            Get
                Return Me.infoTicketField
            End Get
            Set
                Me.infoTicketField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DscItem() As String
            Get
                Return Me.dscItemField
            End Get
            Set
                Me.dscItemField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property QtyItem() As Decimal
            Get
                Return Me.qtyItemField
            End Get
            Set
                Me.qtyItemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property QtyItemSpecified() As Boolean
            Get
                Return Me.qtyItemFieldSpecified
            End Get
            Set
                Me.qtyItemFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property UnmdItem() As String
            Get
                Return Me.unmdItemField
            End Get
            Set
                Me.unmdItemField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PrcItem() As Decimal
            Get
                Return Me.prcItemField
            End Get
            Set
                Me.prcItemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property PrcItemSpecified() As Boolean
            Get
                Return Me.prcItemFieldSpecified
            End Get
            Set
                Me.prcItemFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DescuentoPct() As Decimal
            Get
                Return Me.descuentoPctField
            End Get
            Set
                Me.descuentoPctField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property DescuentoPctSpecified() As Boolean
            Get
                Return Me.descuentoPctFieldSpecified
            End Get
            Set
                Me.descuentoPctFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property DescuentoMonto() As String
            Get
                Return Me.descuentoMontoField
            End Get
            Set
                Me.descuentoMontoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RecargoPct() As Decimal
            Get
                Return Me.recargoPctField
            End Get
            Set
                Me.recargoPctField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property RecargoPctSpecified() As Boolean
            Get
                Return Me.recargoPctFieldSpecified
            End Get
            Set
                Me.recargoPctFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property RecargoMonto() As String
            Get
                Return Me.recargoMontoField
            End Get
            Set
                Me.recargoMontoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>
        Public Property MontoItem() As String
            Get
                Return Me.montoItemField
            End Get
            Set
                Me.montoItemField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoDetalleCdgItem

        Private tpoCodigoField As String

        Private vlrCodigoField As String

        '''<remarks/>
        Public Property TpoCodigo() As String
            Get
                Return Me.tpoCodigoField
            End Get
            Set
                Me.tpoCodigoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VlrCodigo() As String
            Get
                Return Me.vlrCodigoField
            End Get
            Set
                Me.vlrCodigoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoDetalleIndExe

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>
        Item2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("6")>
        Item6
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoDetalleItemEspectaculo

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("01")>
        Item01

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("02")>
        Item02
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoDetalleInfoTicket

        Private folioTicketField As String

        Private fchGeneraField As Date

        Private nmbEventoField As String

        Private tpoTicketField As String

        Private cdgEventoField As String

        Private fchEventoField As Date

        Private lugarEventoField As String

        Private ubicEventoField As String

        Private filaUbicEventoField As String

        Private asntoUbicEventoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property FolioTicket() As String
            Get
                Return Me.folioTicketField
            End Get
            Set
                Me.folioTicketField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FchGenera() As Date
            Get
                Return Me.fchGeneraField
            End Get
            Set
                Me.fchGeneraField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NmbEvento() As String
            Get
                Return Me.nmbEventoField
            End Get
            Set
                Me.nmbEventoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TpoTicket() As String
            Get
                Return Me.tpoTicketField
            End Get
            Set
                Me.tpoTicketField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CdgEvento() As String
            Get
                Return Me.cdgEventoField
            End Get
            Set
                Me.cdgEventoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FchEvento() As Date
            Get
                Return Me.fchEventoField
            End Get
            Set
                Me.fchEventoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property LugarEvento() As String
            Get
                Return Me.lugarEventoField
            End Get
            Set
                Me.lugarEventoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property UbicEvento() As String
            Get
                Return Me.ubicEventoField
            End Get
            Set
                Me.ubicEventoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FilaUbicEvento() As String
            Get
                Return Me.filaUbicEventoField
            End Get
            Set
                Me.filaUbicEventoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AsntoUbicEvento() As String
            Get
                Return Me.asntoUbicEventoField
            End Get
            Set
                Me.asntoUbicEventoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoSubTotInfo

        Private nroSTIField As String

        Private glosaSTIField As String

        Private ordenSTIField As String

        Private subTotNetoSTIField As Decimal

        Private subTotNetoSTIFieldSpecified As Boolean

        Private subTotIVASTIField As Decimal

        Private subTotIVASTIFieldSpecified As Boolean

        Private subTotAdicSTIField As Decimal

        Private subTotAdicSTIFieldSpecified As Boolean

        Private subTotExeSTIField As Decimal

        Private subTotExeSTIFieldSpecified As Boolean

        Private valSubtotSTIField As Decimal

        Private valSubtotSTIFieldSpecified As Boolean

        Private lineasDetaField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property NroSTI() As String
            Get
                Return Me.nroSTIField
            End Get
            Set
                Me.nroSTIField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property GlosaSTI() As String
            Get
                Return Me.glosaSTIField
            End Get
            Set
                Me.glosaSTIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property OrdenSTI() As String
            Get
                Return Me.ordenSTIField
            End Get
            Set
                Me.ordenSTIField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SubTotNetoSTI() As Decimal
            Get
                Return Me.subTotNetoSTIField
            End Get
            Set
                Me.subTotNetoSTIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SubTotNetoSTISpecified() As Boolean
            Get
                Return Me.subTotNetoSTIFieldSpecified
            End Get
            Set
                Me.subTotNetoSTIFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SubTotIVASTI() As Decimal
            Get
                Return Me.subTotIVASTIField
            End Get
            Set
                Me.subTotIVASTIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SubTotIVASTISpecified() As Boolean
            Get
                Return Me.subTotIVASTIFieldSpecified
            End Get
            Set
                Me.subTotIVASTIFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SubTotAdicSTI() As Decimal
            Get
                Return Me.subTotAdicSTIField
            End Get
            Set
                Me.subTotAdicSTIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SubTotAdicSTISpecified() As Boolean
            Get
                Return Me.subTotAdicSTIFieldSpecified
            End Get
            Set
                Me.subTotAdicSTIFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SubTotExeSTI() As Decimal
            Get
                Return Me.subTotExeSTIField
            End Get
            Set
                Me.subTotExeSTIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SubTotExeSTISpecified() As Boolean
            Get
                Return Me.subTotExeSTIFieldSpecified
            End Get
            Set
                Me.subTotExeSTIFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValSubtotSTI() As Decimal
            Get
                Return Me.valSubtotSTIField
            End Get
            Set
                Me.valSubtotSTIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ValSubtotSTISpecified() As Boolean
            Get
                Return Me.valSubtotSTIFieldSpecified
            End Get
            Set
                Me.valSubtotSTIFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("LineasDeta", DataType:="positiveInteger")>
        Public Property LineasDeta() As String()
            Get
                Return Me.lineasDetaField
            End Get
            Set
                Me.lineasDetaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoDscRcgGlobal

        Private nroLinDRField As String

        Private tpoMovField As BOLETADefTypeDocumentoDscRcgGlobalTpoMov

        Private glosaDRField As String

        Private tpoValorField As BOLETADefTypeDocumentoDscRcgGlobalTpoValor

        Private valorDRField As Decimal

        Private indExeDRField As BOLETADefTypeDocumentoDscRcgGlobalIndExeDR

        Private indExeDRFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property NroLinDR() As String
            Get
                Return Me.nroLinDRField
            End Get
            Set
                Me.nroLinDRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TpoMov() As BOLETADefTypeDocumentoDscRcgGlobalTpoMov
            Get
                Return Me.tpoMovField
            End Get
            Set
                Me.tpoMovField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property GlosaDR() As String
            Get
                Return Me.glosaDRField
            End Get
            Set
                Me.glosaDRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TpoValor() As BOLETADefTypeDocumentoDscRcgGlobalTpoValor
            Get
                Return Me.tpoValorField
            End Get
            Set
                Me.tpoValorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorDR() As Decimal
            Get
                Return Me.valorDRField
            End Get
            Set
                Me.valorDRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IndExeDR() As BOLETADefTypeDocumentoDscRcgGlobalIndExeDR
            Get
                Return Me.indExeDRField
            End Get
            Set
                Me.indExeDRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property IndExeDRSpecified() As Boolean
            Get
                Return Me.indExeDRFieldSpecified
            End Get
            Set
                Me.indExeDRFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoDscRcgGlobalTpoMov

        '''<remarks/>
        D

        '''<remarks/>
        R
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoDscRcgGlobalTpoValor

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("%")>
        Item

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("$")>
        Item1
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoDscRcgGlobalIndExeDR

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>
        Item2
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoReferencia

        Private nroLinRefField As String

        Private tpoDocRefField As String

        Private folioRefField As String

        Private codRefField As String

        Private razonRefField As String

        Private codVndorField As String

        Private codCajaField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property NroLinRef() As String
            Get
                Return Me.nroLinRefField
            End Get
            Set
                Me.nroLinRefField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TpoDocRef() As String
            Get
                Return Me.tpoDocRefField
            End Get
            Set
                Me.tpoDocRefField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FolioRef() As String
            Get
                Return Me.folioRefField
            End Get
            Set
                Me.folioRefField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodRef() As String
            Get
                Return Me.codRefField
            End Get
            Set
                Me.codRefField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RazonRef() As String
            Get
                Return Me.razonRefField
            End Get
            Set
                Me.razonRefField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodVndor() As String
            Get
                Return Me.codVndorField
            End Get
            Set
                Me.codVndorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodCaja() As String
            Get
                Return Me.codCajaField
            End Get
            Set
                Me.codCajaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTED

        Private ddField As BOLETADefTypeDocumentoTEDDD

        Private fRMTField As BOLETADefTypeDocumentoTEDFRMT

        Private versionField As String

        Public Sub New()
            MyBase.New
            Me.versionField = "1.0"
        End Sub

        '''<remarks/>
        Public Property DD() As BOLETADefTypeDocumentoTEDDD
            Get
                Return Me.ddField
            End Get
            Set
                Me.ddField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FRMT() As BOLETADefTypeDocumentoTEDFRMT
            Get
                Return Me.fRMTField
            End Get
            Set
                Me.fRMTField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDD

        Private reField As String

        Private tdField As DTEType

        Private fField As String

        Private feField As Date

        Private rrField As String

        Private rSRField As String

        Private mNTField As ULong

        Private iT1Field As String

        Private cAFField As BOLETADefTypeDocumentoTEDDDCAF

        Private tSTEDField As Date

        '''<remarks/>
        Public Property RE() As String
            Get
                Return Me.reField
            End Get
            Set
                Me.reField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TD() As DTEType
            Get
                Return Me.tdField
            End Get
            Set
                Me.tdField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property F() As String
            Get
                Return Me.fField
            End Get
            Set
                Me.fField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property FE() As Date
            Get
                Return Me.feField
            End Get
            Set
                Me.feField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RR() As String
            Get
                Return Me.rrField
            End Get
            Set
                Me.rrField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RSR() As String
            Get
                Return Me.rSRField
            End Get
            Set
                Me.rSRField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MNT() As ULong
            Get
                Return Me.mNTField
            End Get
            Set
                Me.mNTField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IT1() As String
            Get
                Return Me.iT1Field
            End Get
            Set
                Me.iT1Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CAF() As BOLETADefTypeDocumentoTEDDDCAF
            Get
                Return Me.cAFField
            End Get
            Set
                Me.cAFField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TSTED() As Date
            Get
                Return Me.tSTEDField
            End Get
            Set
                Me.tSTEDField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDDCAF

        Private daField As BOLETADefTypeDocumentoTEDDDCAFDA

        Private fRMAField As BOLETADefTypeDocumentoTEDDDCAFFRMA

        Private versionField As String

        Public Sub New()
            MyBase.New
            Me.versionField = "1.0"
        End Sub

        '''<remarks/>
        Public Property DA() As BOLETADefTypeDocumentoTEDDDCAFDA
            Get
                Return Me.daField
            End Get
            Set
                Me.daField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FRMA() As BOLETADefTypeDocumentoTEDDDCAFFRMA
            Get
                Return Me.fRMAField
            End Get
            Set
                Me.fRMAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDDCAFDA

        Private reField As String

        Private rsField As String

        Private tdField As DTEType

        Private rNGField As BOLETADefTypeDocumentoTEDDDCAFDARNG

        Private faField As Date

        Private itemField As Object

        Private iDKField As Long

        '''<remarks/>
        Public Property RE() As String
            Get
                Return Me.reField
            End Get
            Set
                Me.reField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RS() As String
            Get
                Return Me.rsField
            End Get
            Set
                Me.rsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TD() As DTEType
            Get
                Return Me.tdField
            End Get
            Set
                Me.tdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RNG() As BOLETADefTypeDocumentoTEDDDCAFDARNG
            Get
                Return Me.rNGField
            End Get
            Set
                Me.rNGField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property FA() As Date
            Get
                Return Me.faField
            End Get
            Set
                Me.faField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DSAPK", GetType(BOLETADefTypeDocumentoTEDDDCAFDADSAPK)),
     System.Xml.Serialization.XmlElementAttribute("RSAPK", GetType(BOLETADefTypeDocumentoTEDDDCAFDARSAPK))>
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IDK() As Long
            Get
                Return Me.iDKField
            End Get
            Set
                Me.iDKField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDDCAFDARNG

        Private dField As String

        Private hField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property D() As String
            Get
                Return Me.dField
            End Get
            Set
                Me.dField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")>
        Public Property H() As String
            Get
                Return Me.hField
            End Get
            Set
                Me.hField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDDCAFDADSAPK

        Private pField() As Byte

        Private qField() As Byte

        Private gField() As Byte

        Private yField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set
                Me.qField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set
                Me.gField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set
                Me.yField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDDCAFDARSAPK

        Private mField() As Byte

        Private eField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property M() As Byte()
            Get
                Return Me.mField
            End Get
            Set
                Me.mField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property E() As Byte()
            Get
                Return Me.eField
            End Get
            Set
                Me.eField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDDDCAFFRMA

        Private algoritmoField As String

        Private valueField() As Byte

        Public Sub New()
            MyBase.New
            Me.algoritmoField = "SHA1withRSA"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property algoritmo() As String
            Get
                Return Me.algoritmoField
            End Get
            Set
                Me.algoritmoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Partial Public Class BOLETADefTypeDocumentoTEDFRMT

        Private algoritmoField As BOLETADefTypeDocumentoTEDFRMTAlgoritmo

        Private valueField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property algoritmo() As BOLETADefTypeDocumentoTEDFRMTAlgoritmo
            Get
                Return Me.algoritmoField
            End Get
            Set
                Me.algoritmoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sii.cl/SiiDte")>
    Public Enum BOLETADefTypeDocumentoTEDFRMTAlgoritmo

        '''<remarks/>
        SHA1withRSA

        '''<remarks/>
        SHA1withDSA
    End Enum

    'implementación campos adicionales

    '''<remarks/>
    <System.SerializableAttribute(),
    System.ComponentModel.DesignerCategoryAttribute("code"),
    System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class DTEDocumentoAdicional

        Private nodosAField As DTEDocumentoAdicionalNodosA

        '''<remarks/>
        Public Property NodosA() As DTEDocumentoAdicionalNodosA
            Get
                Return Me.nodosAField
            End Get
            Set
                Me.nodosAField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.SerializableAttribute(),
    System.ComponentModel.DesignerCategoryAttribute("code"),
    System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
    Partial Public Class DTEDocumentoAdicionalNodosA

        Private a1Field As String

        Private a2Field As String

        Private a3Field As String

        Private a4Field As String

        Private a5Field As String

        Private a6Field As String

        Private a7Field As String

        Private a8Field As String

        Private a9Field As String

        Private a10Field As String

        Private a11Field As String

        Private a12Field As String

        Private a13Field As String

        Private a14Field As String

        Private a15Field As String

        Private a16Field As String

        Private a17Field As String

        Private a18Field As String

        Private a19Field As String

        Private a20Field As String

        Private a41Field As String

        '''<remarks/>
        Public Property A1() As String
            Get
                Return Me.a1Field
            End Get
            Set
                Me.a1Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A2() As String
            Get
                Return Me.a2Field
            End Get
            Set
                Me.a2Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A3() As String
            Get
                Return Me.a3Field
            End Get
            Set
                Me.a3Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A4() As String
            Get
                Return Me.a4Field
            End Get
            Set
                Me.a4Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A5() As String
            Get
                Return Me.a5Field
            End Get
            Set
                Me.a5Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A6() As String
            Get
                Return Me.a6Field
            End Get
            Set
                Me.a6Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A7() As String
            Get
                Return Me.a7Field
            End Get
            Set
                Me.a7Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A8() As String
            Get
                Return Me.a8Field
            End Get
            Set
                Me.a8Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A9() As String
            Get
                Return Me.a9Field
            End Get
            Set
                Me.a9Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A10() As String
            Get
                Return Me.a10Field
            End Get
            Set
                Me.a10Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A11() As String
            Get
                Return Me.a11Field
            End Get
            Set
                Me.a11Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A12() As String
            Get
                Return Me.a12Field
            End Get
            Set
                Me.a12Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A13() As String
            Get
                Return Me.a13Field
            End Get
            Set
                Me.a13Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A14() As String
            Get
                Return Me.a14Field
            End Get
            Set
                Me.a14Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A15() As String
            Get
                Return Me.a15Field
            End Get
            Set
                Me.a15Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A16() As String
            Get
                Return Me.a16Field
            End Get
            Set
                Me.a16Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A17() As String
            Get
                Return Me.a17Field
            End Get
            Set
                Me.a17Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A18() As String
            Get
                Return Me.a18Field
            End Get
            Set
                Me.a18Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A19() As String
            Get
                Return Me.a19Field
            End Get
            Set
                Me.a19Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A20() As String
            Get
                Return Me.a20Field
            End Get
            Set
                Me.a20Field = Value
            End Set
        End Property

        '''<remarks/>
        Public Property A41() As String
            Get
                Return Me.a20Field
            End Get
            Set
                Me.a20Field = Value
            End Set
        End Property

    End Class

End Namespace