'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=4.7.2053.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
 System.Xml.Serialization.XmlRootAttribute("Signature", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
Partial Public Class SignatureType
    
    Private signedInfoField As SignatureTypeSignedInfo
    
    Private signatureValueField() As Byte
    
    Private keyInfoField As SignatureTypeKeyInfo
    
    '''<remarks/>
    Public Property SignedInfo() As SignatureTypeSignedInfo
        Get
            Return Me.signedInfoField
        End Get
        Set
            Me.signedInfoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property SignatureValue() As Byte()
        Get
            Return Me.signatureValueField
        End Get
        Set
            Me.signatureValueField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property KeyInfo() As SignatureTypeKeyInfo
        Get
            Return Me.keyInfoField
        End Get
        Set
            Me.keyInfoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfo
    
    Private canonicalizationMethodField As SignatureTypeSignedInfoCanonicalizationMethod
    
    Private signatureMethodField As SignatureTypeSignedInfoSignatureMethod
    
    Private referenceField As SignatureTypeSignedInfoReference
    
    '''<remarks/>
    Public Property CanonicalizationMethod() As SignatureTypeSignedInfoCanonicalizationMethod
        Get
            Return Me.canonicalizationMethodField
        End Get
        Set
            Me.canonicalizationMethodField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SignatureMethod() As SignatureTypeSignedInfoSignatureMethod
        Get
            Return Me.signatureMethodField
        End Get
        Set
            Me.signatureMethodField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Reference() As SignatureTypeSignedInfoReference
        Get
            Return Me.referenceField
        End Get
        Set
            Me.referenceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfoCanonicalizationMethod
    
    Private algorithmField As String
    
    Public Sub New()
        MyBase.New
        Me.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
    Public Property Algorithm() As String
        Get
            Return Me.algorithmField
        End Get
        Set
            Me.algorithmField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfoSignatureMethod
    
    Private algorithmField As SignatureTypeSignedInfoSignatureMethodAlgorithm
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Algorithm() As SignatureTypeSignedInfoSignatureMethodAlgorithm
        Get
            Return Me.algorithmField
        End Get
        Set
            Me.algorithmField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Public Enum SignatureTypeSignedInfoSignatureMethodAlgorithm
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")>  _
    httpwwww3org200009xmldsigrsasha1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#dsa-sha1")>  _
    httpwwww3org200009xmldsigdsasha1
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfoReference
    
    Private transformsField As SignatureTypeSignedInfoReferenceTransforms
    
    Private digestMethodField As SignatureTypeSignedInfoReferenceDigestMethod
    
    Private digestValueField() As Byte
    
    Private uRIField As String
    
    '''<remarks/>
    Public Property Transforms() As SignatureTypeSignedInfoReferenceTransforms
        Get
            Return Me.transformsField
        End Get
        Set
            Me.transformsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DigestMethod() As SignatureTypeSignedInfoReferenceDigestMethod
        Get
            Return Me.digestMethodField
        End Get
        Set
            Me.digestMethodField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property DigestValue() As Byte()
        Get
            Return Me.digestValueField
        End Get
        Set
            Me.digestValueField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
    Public Property URI() As String
        Get
            Return Me.uRIField
        End Get
        Set
            Me.uRIField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfoReferenceTransforms
    
    Private transformField As SignatureTypeSignedInfoReferenceTransformsTransform
    
    '''<remarks/>
    Public Property Transform() As SignatureTypeSignedInfoReferenceTransformsTransform
        Get
            Return Me.transformField
        End Get
        Set
            Me.transformField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfoReferenceTransformsTransform
    
    Private algorithmField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
    Public Property Algorithm() As String
        Get
            Return Me.algorithmField
        End Get
        Set
            Me.algorithmField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeSignedInfoReferenceDigestMethod
    
    Private algorithmField As String
    
    Public Sub New()
        MyBase.New
        Me.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
    Public Property Algorithm() As String
        Get
            Return Me.algorithmField
        End Get
        Set
            Me.algorithmField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeKeyInfo
    
    Private keyValueField As SignatureTypeKeyInfoKeyValue
    
    Private x509DataField As SignatureTypeKeyInfoX509Data
    
    '''<remarks/>
    Public Property KeyValue() As SignatureTypeKeyInfoKeyValue
        Get
            Return Me.keyValueField
        End Get
        Set
            Me.keyValueField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property X509Data() As SignatureTypeKeyInfoX509Data
        Get
            Return Me.x509DataField
        End Get
        Set
            Me.x509DataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeKeyInfoKeyValue
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(SignatureTypeKeyInfoKeyValueDSAKeyValue)),  _
     System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(SignatureTypeKeyInfoKeyValueRSAKeyValue))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeKeyInfoKeyValueDSAKeyValue
    
    Private pField() As Byte
    
    Private qField() As Byte
    
    Private gField() As Byte
    
    Private yField() As Byte
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property P() As Byte()
        Get
            Return Me.pField
        End Get
        Set
            Me.pField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property Q() As Byte()
        Get
            Return Me.qField
        End Get
        Set
            Me.qField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property G() As Byte()
        Get
            Return Me.gField
        End Get
        Set
            Me.gField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property Y() As Byte()
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeKeyInfoKeyValueRSAKeyValue
    
    Private modulusField() As Byte
    
    Private exponentField() As Byte
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property Modulus() As Byte()
        Get
            Return Me.modulusField
        End Get
        Set
            Me.modulusField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property Exponent() As Byte()
        Get
            Return Me.exponentField
        End Get
        Set
            Me.exponentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
Partial Public Class SignatureTypeKeyInfoX509Data
    
    Private x509CertificateField() As Byte
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property X509Certificate() As Byte()
        Get
            Return Me.x509CertificateField
        End Get
        Set
            Me.x509CertificateField = value
        End Set
    End Property
End Class

